// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABvIrG1OX1sUASKdKBfdoK3-0g5vpoWzE',
    appId: '1:779192762130:web:546f83d6b8a1cd61b5fdcb',
    messagingSenderId: '779192762130',
    projectId: 'fir-demo-app-30109',
    authDomain: 'fir-demo-app-30109.firebaseapp.com',
    storageBucket: 'fir-demo-app-30109.appspot.com',
    measurementId: 'G-ZGEE5DJHSZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvr5AN46EbCSDfmSkTNxc-8N6_S_bDyKg',
    appId: '1:779192762130:android:f32a941b8a46701ab5fdcb',
    messagingSenderId: '779192762130',
    projectId: 'fir-demo-app-30109',
    storageBucket: 'fir-demo-app-30109.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjIuktXi7kP4Dw7HWY73-rE1ygv1Numpg',
    appId: '1:779192762130:ios:ab56bb562873ec32b5fdcb',
    messagingSenderId: '779192762130',
    projectId: 'fir-demo-app-30109',
    storageBucket: 'fir-demo-app-30109.appspot.com',
    iosClientId: '779192762130-tr157mlkjqoadckgo14rtaeg6kt4h3l0.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterDemoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjIuktXi7kP4Dw7HWY73-rE1ygv1Numpg',
    appId: '1:779192762130:ios:ab56bb562873ec32b5fdcb',
    messagingSenderId: '779192762130',
    projectId: 'fir-demo-app-30109',
    storageBucket: 'fir-demo-app-30109.appspot.com',
    iosClientId: '779192762130-tr157mlkjqoadckgo14rtaeg6kt4h3l0.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterDemoApp',
  );
}
